const http = require('http');

const unitQuestionsData = {
    // 1. MATRICES AND CALCULUS
    "Matrices and Calculus": {
        "Unit 1": [
            { "question": "Define rank of a matrix. Find the rank of A = [[1, 2, 3], [2, 4, 6], [3, 6, 9]].", "year": "2023", "priority": "high" },
            { "question": "Solve the system: x+y+z=6, x+2y+3z=14, x+4y+9z=36.", "year": "2023", "priority": "high" },
            { "question": "Find Eigen values and Eigen vectors of [[3, -1, 1], [-1, 5, -1], [1, -1, 3]].", "year": "2024", "priority": "high" },
            { "question": "Define Hermitian and Skew-Hermitian matrices with examples.", "year": "2022", "priority": "normal" },
            { "question": "Discuss the consistency of linear equations using rank.", "year": "2022", "priority": "normal" },
            { "question": "Find the inverse of matrix A using Cayley-Hamilton theorem.", "year": "2021", "priority": "high" },
            { "question": "What are orthogonal matrices? Properties.", "year": "2023", "priority": "normal" },
            { "question": "Explain procedure to diagonalize a matrix.", "year": "2024", "priority": "high" },
            { "question": "Solve system using Gauss-Seidel method.", "year": "2022", "priority": "normal" },
            { "question": "Find rank using Normal form.", "year": "2021", "priority": "normal" },
        ],
        "Unit 2": [
            { "question": "Verify Cayley-Hamilton theorem for A = [[1, 2], [2, 1]].", "year": "2023", "priority": "high" },
            { "question": "Reduce quadratic form 3x^2+5y^2+3z^2 to canonical form.", "year": "2024", "priority": "high" },
            { "question": "Find nature of quadratic form.", "year": "2022", "priority": "normal" },
            { "question": "State properties of Eigen values.", "year": "2021", "priority": "normal" },
            { "question": "Find modal matrix for given A.", "year": "2023", "priority": "high" },
            { "question": "Diagonalize the matrix A.", "year": "2022", "priority": "high" },
            { "question": "Calculate A^4 using Cayley-Hamilton theorem.", "year": "2024", "priority": "high" },
            { "question": "Reduce to canonical form using Orthogonal transformation.", "year": "2021", "priority": "normal" },
        ],
        "Unit 3": [
            { "question": "Test convergence of Sigma (n=1 to infinity) (n+1)/(n^3).", "year": "2023", "priority": "high" },
            { "question": "State and prove Rolle's Mean Value Theorem.", "year": "2023", "priority": "high" },
            { "question": "Expand e^x sin y using Taylor's theorem.", "year": "2024", "priority": "high" },
            { "question": "Test convergence using Ratio Test.", "year": "2022", "priority": "normal" },
            { "question": "Explain Lagrange's Mean Value Theorem.", "year": "2021", "priority": "high" },
            { "question": "Find maxima and minima of x^3 + y^3 - 3axy.", "year": "2022", "priority": "high" },
            { "question": "Discuss geometrical interpretation of Rolle's theorem.", "year": "2023", "priority": "normal" },
            { "question": "Expand log(1+x) using Maclaurin's series.", "year": "2024", "priority": "normal" },
        ],
        "Unit 4": [
            { "question": "Evaluate Integral (0 to pi/2) log(sin x) dx.", "year": "2023", "priority": "high" },
            { "question": "Find the volume of solid generated by revolution of y^2 = x(x-2)^2.", "year": "2023", "priority": "high" },
            { "question": "Evaluate double integral over circle x^2+y^2=1.", "year": "2024", "priority": "high" },
            { "question": "Change order of integration.", "year": "2022", "priority": "high" },
            { "question": "Evaluate Gamma(1/2).", "year": "2021", "priority": "normal" },
            { "question": "Find area enclosed by the curve r=a(1+cos theta).", "year": "2022", "priority": "normal" },
            { "question": "Evaluate Beta function B(m,n).", "year": "2023", "priority": "normal" },
        ],
        "Unit 5": [
            { "question": "Method of variation of parameters to solve ODE.", "year": "2023", "priority": "high" },
            { "question": "Solve (D^2 + 4)y = tan 2x.", "year": "2024", "priority": "high" },
            { "question": "Solve dy/dx + Py = Q (Linear Equation).", "year": "2022", "priority": "normal" },
            { "question": "Solve exact differential equation.", "year": "2021", "priority": "normal" },
            { "question": "Find orthogonal trajectories of curve family.", "year": "2023", "priority": "high" },
            { "question": "Solve (D^2 - 3D + 2)y = e^(3x).", "year": "2022", "priority": "high" },
            { "question": "Newton's Law of Cooling verification.", "year": "2024", "priority": "normal" },
        ],
    },
    // 2. ENGINEERING CHEMISTRY
    "Engineering Chemistry": {
        "Unit 1": [
            { "question": "Explain Atomic Structure and Chemical Bonding.", "year": "2023", "priority": "high" },
            { "question": "Discuss MOT for N2 and O2 molecules.", "year": "2024", "priority": "high" },
            { "question": "Explain Crystal Field Theory (CFT).", "year": "2022", "priority": "high" },
            { "question": "What are postulates of Molecular Orbital Theory?", "year": "2021", "priority": "normal" },
            { "question": "Calculate bond order of CO molecule.", "year": "2023", "priority": "normal" },
            { "question": "Explain splitting of d-orbitals in octahedral field.", "year": "2022", "priority": "high" },
            { "question": "Explain Spectrochemical series.", "year": "2022", "priority": "high" },
        ],
        "Unit 2": [
            { "question": "Derive Nernst Equation.", "year": "2022", "priority": "high" },
            { "question": "Explain construction of Calomel Electrode.", "year": "2023", "priority": "high" },
            { "question": "Discuss theories of Corrosion.", "year": "2024", "priority": "high" },
            { "question": "Explain Galvanic Cell working.", "year": "2021", "priority": "normal" },
            { "question": "Factors affecting corrosion.", "year": "2022", "priority": "high" },
            { "question": "Working of Lithium Ion battery.", "year": "2022", "priority": "high" },
        ],
        "Unit 3": [
            { "question": "Explain synthesis of Nylon 6,6.", "year": "2023", "priority": "high" },
            { "question": "Difference between Thermoplastics and Thermosetting plastics.", "year": "2024", "priority": "high" },
            { "question": "Explain mechanism of Free Radical Polymerization.", "year": "2022", "priority": "high" },
            { "question": "Write notes on Biodegradable polymers.", "year": "2023", "priority": "normal" },
            { "question": "Explain Vulcanization of Rubber.", "year": "2021", "priority": "normal" },
            { "question": "Preparation and properties of Bakelite.", "year": "2022", "priority": "high" },
        ],
        "Unit 4": [
            { "question": "Explain EDTA method for hardness of water.", "year": "2023", "priority": "high" },
            { "question": "Describe Reverse Osmosis process.", "year": "2024", "priority": "high" },
            { "question": "Difference between temporary and permanent hardness.", "year": "2022", "priority": "normal" },
            { "question": "Explain Zeolite process.", "year": "2021", "priority": "normal" },
            { "question": "What is Breakpoint Chlorination?", "year": "2022", "priority": "high" },
            { "question": "Explain Potable Water specifications.", "year": "2023", "priority": "normal" },
        ],
        "Unit 5": [
            { "question": "Explain different types of Spectroscopic techniques.", "year": "2023", "priority": "high" },
            { "question": "Principle and application of UV-Visible Spectroscopy.", "year": "2024", "priority": "high" },
            { "question": "Explain NMR Spectroscopy principle.", "year": "2022", "priority": "high" },
            { "question": "What is Beer-Lambert's Law?", "year": "2021", "priority": "high" },
            { "question": "Applications of IR Spectroscopy.", "year": "2023", "priority": "normal" },
            { "question": "Explain MRI principle.", "year": "2022", "priority": "normal" },
        ],
    },
    // 3. PROGRAMMING FOR PROBLEM SOLVING (PPS)
    "Programming for Problem Solving": {
        "Unit 1": [
            { "question": "Draw flowchart to find max of 3 numbers.", "year": "2023", "priority": "normal" },
            { "question": "Explain various Data Types in C.", "year": "2024", "priority": "high" },
            { "question": "Explain structure of C program.", "year": "2022", "priority": "normal" },
            { "question": "What are the different types of Operators in C?", "year": "2021", "priority": "high" },
            { "question": "Explain Type Conversion with example.", "year": "2023", "priority": "high" },
        ],
        "Unit 2": [
            { "question": "Explain Switch-Case statement with example.", "year": "2023", "priority": "high" },
            { "question": "Difference between While and Do-While loop.", "year": "2024", "priority": "high" },
            { "question": "Program to check if number is Prime.", "year": "2022", "priority": "high" },
            { "question": "Explain break and continue statements.", "year": "2021", "priority": "normal" },
            { "question": "Pattern printing program (Star pyramid).", "year": "2023", "priority": "normal" },
        ],
        "Unit 3": [
            { "question": "Explain 1D and 2D arrays with syntax.", "year": "2023", "priority": "high" },
            { "question": "Write program for Matrix Multiplication.", "year": "2024", "priority": "high" },
            { "question": "Explain String handling functions in C.", "year": "2022", "priority": "high" },
            { "question": "Selection Sort program.", "year": "2021", "priority": "normal" },
            { "question": "What are Arrays of Strings?", "year": "2022", "priority": "normal" },
        ],
        "Unit 4": [
            { "question": "Define Function. Types of functions.", "year": "2023", "priority": "high" },
            { "question": "Explain Recursion with Factorial example.", "year": "2024", "priority": "high" },
            { "question": "Call by Value vs Call by Reference.", "year": "2022", "priority": "high" },
            { "question": "Explain Storage Classes in C.", "year": "2021", "priority": "high" },
            { "question": "Passing arrays to functions.", "year": "2023", "priority": "normal" },
        ],
        "Unit 5": [
            { "question": "Explain Structures vs Unions.", "year": "2023", "priority": "high" },
            { "question": "Explain Pointers concept in C.", "year": "2024", "priority": "high" },
            { "question": "File handling functions (fopen, fclose).", "year": "2022", "priority": "high" },
            { "question": "Explain Dynamic Memory Allocation (malloc, calloc).", "year": "2021", "priority": "high" },
            { "question": "Command line arguments explanation.", "year": "2022", "priority": "normal" },
        ],
    },
    // 4. BASIC ELECTRONIC ENGINEERING (BEE)
    "Basic Electronic Engineering": {
        "Unit 1": [
            { "question": "Explain PN Junction Diode V-I characteristics.", "year": "2023", "priority": "high" },
            { "question": "Working of Zener Diode as regulator.", "year": "2024", "priority": "high" },
            { "question": "Explain Full Wave Bridge Rectifier.", "year": "2022", "priority": "high" },
            { "question": "Difference between Intrinsic and Extrinsic semiconductor.", "year": "2021", "priority": "normal" },
            { "question": "Explain Clipper and Clamper circuits.", "year": "2023", "priority": "normal" },
        ],
        "Unit 2": [
            { "question": "Explain Input/Output characteristics of BJT in CE configuration.", "year": "2023", "priority": "high" },
            { "question": "Explain construction and operation of JFET.", "year": "2024", "priority": "high" },
            { "question": "Difference between BJT and FET.", "year": "2022", "priority": "high" },
            { "question": "Explain MOSFET construction (Enhancement mode).", "year": "2021", "priority": "high" },
            { "question": "Transistor as a switch.", "year": "2023", "priority": "normal" },
        ],
        "Unit 3": [
            { "question": "Explain concept of Feedback in amplifiers.", "year": "2023", "priority": "high" },
            { "question": "Derive expression for voltage gain of CE amplifier.", "year": "2024", "priority": "high" },
            { "question": "Explain working of RC Phase Shift Oscillator.", "year": "2022", "priority": "high" },
            { "question": "Advantages of Negative Feedback.", "year": "2021", "priority": "normal" },
            { "question": "Explain Hartley Oscillator.", "year": "2022", "priority": "normal" },
        ],
        "Unit 4": [
            { "question": "Explain Ideal Op-Amp characteristics.", "year": "2023", "priority": "high" },
            { "question": "Op-Amp as Iverting and Non-Inverting Amplifier.", "year": "2024", "priority": "high" },
            { "question": "Op-Amp as Integrator and Differentiator.", "year": "2022", "priority": "high" },
            { "question": "Explain CMRR and Slew Rate.", "year": "2021", "priority": "normal" },
            { "question": "Op-Amp as Comparator.", "year": "2023", "priority": "normal" },
        ],
        "Unit 5": [
            { "question": "Explain construction of CRT.", "year": "2023", "priority": "high" },
            { "question": "Block diagram of CRO.", "year": "2024", "priority": "high" },
            { "question": "Explain measurement of Voltage and Frequency using CRO.", "year": "2022", "priority": "high" },
            { "question": "Working of Digital Multimeter.", "year": "2021", "priority": "normal" },
            { "question": "Block diagram of Function Generator.", "year": "2022", "priority": "normal" },
        ],
    },
    // 5. APPLIED PHYSICS
    "Applied Physics": {
        "Unit 1": [
            { "question": "Explain Davisson-Germer experiment.", "year": "2023", "priority": "high" },
            { "question": "Derive Schrodinger's Time Independent Wave Equation.", "year": "2024", "priority": "high" },
            { "question": "Explain Photoelectric effect.", "year": "2022", "priority": "normal" },
            { "question": "Physical significance of Wave Function.", "year": "2021", "priority": "normal" },
            { "question": "Explain Heisenberg Uncertainty Principle.", "year": "2022", "priority": "high" },
        ],
        "Unit 2": [
            { "question": "Explain Kronig-Penney Model.", "year": "2023", "priority": "high" },
            { "question": "Classify materials based on Band Theory.", "year": "2024", "priority": "high" },
            { "question": "Explain Fermi-Dirac distribution function.", "year": "2022", "priority": "normal" },
            { "question": "Explain Effective Mass concept.", "year": "2021", "priority": "normal" },
            { "question": "Density of states derivation.", "year": "2023", "priority": "high" },
        ],
        "Unit 3": [
            { "question": "Derive continuity equation for semiconductors.", "year": "2023", "priority": "high" },
            { "question": "Explain Hall Effect and its applications.", "year": "2024", "priority": "high" },
            { "question": "Explain Direct and Indirect Bandgap semiconductors.", "year": "2022", "priority": "high" },
            { "question": "V-I characteristics of PN junction.", "year": "2021", "priority": "normal" },
            { "question": "Working of LED and Solar Cell.", "year": "2022", "priority": "high" },
        ],
        "Unit 4": [
            { "question": "Explain different types of Polarization.", "year": "2023", "priority": "high" },
            { "question": "Explain Hysteresis Loop for ferromagnetic materials.", "year": "2024", "priority": "high" },
            { "question": "Derive Clausius-Mosotti relation.", "year": "2022", "priority": "high" },
            { "question": "Explain Soft and Hard magnetic materials.", "year": "2021", "priority": "normal" },
            { "question": "Explain Domain theory of ferromagnetism.", "year": "2023", "priority": "high" },
        ],
        "Unit 5": [
            { "question": "Explain Laser principle (Stimulated Emission).", "year": "2023", "priority": "high" },
            { "question": "Describe construction of Optical Fiber.", "year": "2024", "priority": "high" },
            { "question": "Explain Ruby Laser or He-Ne Laser.", "year": "2022", "priority": "high" },
            { "question": "Explain Total Internal Reflection principle.", "year": "2021", "priority": "normal" },
            { "question": "Applications of Lasers and Optical Fibers.", "year": "2022", "priority": "normal" },
        ],
    },
    // 6. ENGLISH
    "English for Skill Enhancement": {
        "Unit 1": [
            { "question": "Summarize 'The Raman Effect'.", "year": "2023", "priority": "high" },
            { "question": "Explain vital signs of good communication.", "year": "2024", "priority": "high" },
            { "question": "Write a paragraph on 'Importance of Technology'.", "year": "2022", "priority": "normal" },
            { "question": "Explain types of listening.", "year": "2021", "priority": "normal" },
            { "question": "Common errors in Nouns and Pronouns.", "year": "2023", "priority": "normal" },
        ],
        "Unit 2": [
            { "question": "Summary of 'Ancient Architecture in India'.", "year": "2023", "priority": "high" },
            { "question": "Write a letter to Principal asking for leave.", "year": "2024", "priority": "high" },
            { "question": "Explain precise writing.", "year": "2022", "priority": "normal" },
            { "question": "Common errors in Adjectives.", "year": "2021", "priority": "normal" },
            { "question": "Write an email to HR for job application.", "year": "2022", "priority": "high" },
        ],
        "Unit 3": [
            { "question": "Summary of 'Blue Jeans'.", "year": "2023", "priority": "high" },
            { "question": "Explain technical report writing.", "year": "2024", "priority": "high" },
            { "question": "Difference between active and passive voice.", "year": "2022", "priority": "normal" },
            { "question": "Describe a process (e.g., making tea).", "year": "2021", "priority": "normal" },
            { "question": "Write a covering letter.", "year": "2023", "priority": "high" },
        ],
        "Unit 4": [
            { "question": "Summary of 'What Should You Be Eating'.", "year": "2023", "priority": "high" },
            { "question": "Explain Essay writing structure.", "year": "2024", "priority": "high" },
            { "question": "Common errors in Prepositions.", "year": "2022", "priority": "normal" },
            { "question": "Write a dialogue between two friends.", "year": "2021", "priority": "normal" },
            { "question": "Information transfer (Chart to Text).", "year": "2022", "priority": "high" },
        ],
        "Unit 5": [
            { "question": "Summary of 'How to Regenerate Agriculture'.", "year": "2023", "priority": "high" },
            { "question": "Write a CV/Resume for a software job.", "year": "2024", "priority": "high" },
            { "question": "Explain the art of making presentations.", "year": "2022", "priority": "high" },
            { "question": "Group Discussion etiquette.", "year": "2021", "priority": "high" },
            { "question": "Common errors in Tenses.", "year": "2023", "priority": "normal" },
        ],
    },
    // 7. DATA STRUCTURES (DS)
    "Data Structures (DS)": {
        "Unit 1": [
            { "question": "Explain Single Linked List operations.", "year": "2023", "priority": "high" },
            { "question": "Convert (A+B)*(C-D) to postfix.", "year": "2023", "priority": "high" },
            { "question": "Compare Linear vs Non-Linear DS.", "year": "2024", "priority": "normal" },
            { "question": "Algorithm to insert node at end of SLL.", "year": "2022", "priority": "normal" },
            { "question": "Explain Sparse Matrix representation.", "year": "2021", "priority": "normal" },
            { "question": "Reverse a Singly Linked List.", "year": "2022", "priority": "high" },
            { "question": "Explain time complexity analysis.", "year": "2023", "priority": "normal" },
            { "question": "Difference between Array and Linked List.", "year": "2024", "priority": "high" },
            { "question": "Delete a node from Circular Linked List.", "year": "2021", "priority": "normal" },
            { "question": "Evaluate postfix expression.", "year": "2023", "priority": "high" },
        ],
        "Unit 2": [
            { "question": "Implementation of Stack using Arrays.", "year": "2023", "priority": "normal" },
            { "question": "Implementation of Queue using Linked List.", "year": "2024", "priority": "high" },
            { "question": "Explain Circular Queue operations.", "year": "2022", "priority": "high" },
            { "question": "Algorithm for Infix to Postfix conversion.", "year": "2021", "priority": "high" },
            { "question": "Reverse string using Stack.", "year": "2023", "priority": "normal" },
            { "question": "Explain Double Ended Queue (Deque).", "year": "2022", "priority": "normal" },
            { "question": "Tower of Hanoi problem using recursion.", "year": "2021", "priority": "high" },
            { "question": "Applications of Stack data structure.", "year": "2022", "priority": "normal" },
        ],
        "Unit 3": [
            { "question": "Explain Quick Sort with example.", "year": "2023", "priority": "high" },
            { "question": "Merge Sort algorithm and complexity.", "year": "2024", "priority": "high" },
            { "question": "Implementation of Binary Search.", "year": "2022", "priority": "high" },
            { "question": "Bubble Sort vs Selection Sort.", "year": "2021", "priority": "normal" },
            { "question": "Explain Heap Sort algorithm.", "year": "2023", "priority": "high" },
            { "question": "Insertion Sort logic and code.", "year": "2022", "priority": "normal" },
            { "question": "What is Stable Sorting?", "year": "2024", "priority": "normal" },
            { "question": "Explain Linear Search logic.", "year": "2021", "priority": "normal" },
        ],
        "Unit 4": [
            { "question": "Define Binary Tree and BST.", "year": "2023", "priority": "high" },
            { "question": "Explain Tree Traversal techniques (Inorder, Pre, Post).", "year": "2024", "priority": "high" },
            { "question": "Construct BST from given elements.", "year": "2022", "priority": "high" },
            { "question": "Define AVL Tree and rotations.", "year": "2021", "priority": "high" },
            { "question": "Explain Graph terminology.", "year": "2023", "priority": "normal" },
            { "question": "Explain BFS and DFS algorithms.", "year": "2022", "priority": "high" },
            { "question": "Define Threaded Binary Tree.", "year": "2024", "priority": "normal" },
        ],
        "Unit 5": [
            { "question": "Explain Minimum Spanning Tree.", "year": "2023", "priority": "normal" },
            { "question": "Prim's Algorithm with example.", "year": "2024", "priority": "high" },
            { "question": "Kruskal's Algorithm with example.", "year": "2022", "priority": "high" },
            { "question": "Dijkstra's Algorithm for Shortest Path.", "year": "2021", "priority": "high" },
            { "question": "Explain Hashing and Collision resolution.", "year": "2023", "priority": "high" },
            { "question": "B-Tree and B+ Tree introduction.", "year": "2022", "priority": "normal" },
            { "question": "Explain Double Hashing.", "year": "2024", "priority": "normal" },
        ],
    },
};

const BATCH_SIZE = 10;

function postPYQ(data) {
    return new Promise((resolve, reject) => {
        const postData = JSON.stringify(data);

        const options = {
            hostname: 'localhost',
            port: 5000,
            path: '/api/admin/pyq',
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Content-Length': Buffer.byteLength(postData)
            }
        };

        const req = http.request(options, (res) => {
            res.on('data', () => { }); // Consume
            res.on('end', () => {
                resolve(res.statusCode === 200);
            });
        });

        req.on('error', (e) => {
            console.error(`❌ Request Error: ${e.message}`);
            resolve(false);
        });

        req.write(postData);
        req.end();
    });
}

async function run() {
    console.log("Preparing PYQ Data...");
    const allQuestions = [];

    for (const [subject, units] of Object.entries(unitQuestionsData)) {
        for (const [unitKey, questions] of Object.entries(units)) {
            const unit = unitKey.replace("Unit ", ""); // "Unit 1" -> "1"

            for (const q of questions) {
                allQuestions.push({
                    subject,
                    unit,
                    question: q.question,
                    year: q.year,
                    priority: q.priority
                });
            }
        }
    }

    console.log(`Generating ${allQuestions.length} PYQs. Sending to API...`);

    let successCount = 0;
    for (let i = 0; i < allQuestions.length; i++) {
        const q = allQuestions[i];
        if (i % 20 === 0) console.log(`Processing ${i}/${allQuestions.length}...`);

        // Send one by one (API is single create) or modify API to accept batch.
        // Current API /pyq accepts single object.
        const success = await postPYQ(q);
        if (success) successCount++;
    }

    console.log(`✅ Seeded ${successCount}/${allQuestions.length} PYQs.`);
}

run();
